# Generated by Django 4.1 on 2022-08-29 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('color', models.CharField(max_length=500, null=True)),
                ('timeZone', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
