# Generated by Django 4.1 on 2022-08-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='timeZone',
            new_name='time_zone',
        ),
    ]
