# Generated by Django 4.1 on 2022-08-30 09:06

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_timezone_cat_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Nairobi'),
        ),
    ]
