# Generated by Django 4.1 on 2022-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='time_zone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
