# Generated by Django 4.1 on 2022-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_cat_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='time_zone',
            new_name='time_zonee',
        ),
    ]
